services:
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: godsonjay1/trading-db:latest
    container_name: trading-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trust_trading
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend/trading
      dockerfile: Dockerfile
    image: godsonjay1/trading-backend:latest
    container_name: trading-backend
    depends_on:
      - db
    ports:
      - "5455:5455"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/trust_trading
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: godsonjay1/trading-frontend:latest
    container_name: trading-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:

